{application,serv,
             [{description,"thrift base erlang rpc server"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{serv_app,[]}},
              {env,[]},
              {modules,[account_types,captcha_types,date_types,location_types,
                        nakama_types,profile_types,serv,serv_app,serv_sup,
                        service_thrift,time_types,user_types]}]}.
